---
title: "Covid91 vaccine study Final2024"
author: "Lele Nicholson!"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="finalSumr2024.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

## Males

By doing my research, I've analyzed the Null Hypothesis and we would reject for being equal to or less than to 1. For the alternative Hypothesis is actually greater than 1, (2.21) and (3.61). So therefore they are not equal to 1. The P-value is 2.2e-16. After putting everything together The vaccine worked way than the placebo on the infected. While it did nothing to the Okay meaning it would work 95%.

## Females

By doing my research, I've analyzed the Null Hypothesis and we would reject it because it is way too small. but for the alternative Hypothesis is actually smaller than 1 due to the confidence being (1.49) and (2.32). So therefore they are not equal to 1. The P-value is 1.24e-08 After putting everything together The vaccine worked less than the placebo on the infected. while it did nothing to the Okay meaning is did not work 95$.

## LGBTQ

While doing my Research i found we can not accept or reject the Null because it is not equal to 1 and neither is alternative because there is no data. The p-value is 1.

## Druggies

After doing my Research, I found out here we can not accept or reject the Null because it is not equal to 1 too and neither is alternative because there is no data. The p-value is also 1.


# Overall Results and Conclusions

In overall results my conculsion is the data about the vaccine was sucsessful and Statisically was effective between Males and Females because we do not have enough data for the LGBTQ and the Drugusers to get their Null and Alternative Hypothesis. But the P-value was 1 for the LGBTQ and Drugusers. The Males were stronger (2.82) While Females wasn't Strong enough (1.86).
